name: CI & Release

on:
  push:
    branches: [main]
    tags: ["v*.*.*"] # on version tags like v1.0.0
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests & Benchmarks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.2]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: "go-mod"

      - name: Install GNU Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Tidy modules
        run: make tidy

      - name: Run unit tests
        run: go test ./... -timeout 2m

      - name: Run benchmarks
        run: go test ./internal/compressor -bench=BenchmarkCompressDefault -benchtime=1s

      - name: Build all platforms
        run: make

      - name: Archive dist/
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifacts
          path: dist/

  release:
    name: Create GitHub Release
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.24.2
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.2

      - name: Install GNU Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build all platforms
        run: make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
